### ISSUE TITLE
Unterminated string constant

### ISSUE THREAD

**Issue by daena94** [TheRedBalls/Final-Project#23]
gives error code "Unterminated string constant" even though all brackets have matches

```
processing.app.SketchException: Unterminated string constant
    at processing.mode.java.preproc.PdePreprocessor.checkForUnterminatedMultilineComment(PdePreprocessor.java:843)
    at processing.mode.java.preproc.PdePreprocessor.write(PdePreprocessor.java:918)
    at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:290)
    at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:193)
    at processing.mode.java.JavaBuild.build(JavaBuild.java:152)
    at processing.mode.java.JavaBuild.build(JavaBuild.java:131)
    at processing.mode.java.JavaMode.handleLaunch(JavaMode.java:151)
    at processing.mode.java.JavaEditor$35.run(JavaEditor.java:1087)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by codethejason** [comment]
Fixed #26.
